development:
  adapter: postgresql
  encoding: unicode
  database: ubuntu
  pool: 5
  username: ubuntu
  password: ubuntu
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ubuntu_test
  pool: 5
  username: ubuntu
  password: ubuntu
  host: localhost
  
production:
  adapter: postgresql
  encoding: unicode
  database: ubuntu_production
  pool: 5
  username: ubuntu
  password: ubuntu
  host: localhost
