development:
  adapter: postgresql
  encoding: unicode
  database: ubuntu
  pool: 5
  username: ubuntu
  password: ubuntu

test:
  adapter: postgresql
  encoding: unicode
  database: ubuntu_test
  pool: 5
  username: ubuntu
  password: ubuntu